# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhzSyC8zqf-VAfPDjoXR5bC6gtDzryGe

# ==================================================
# BÀI 1.2.2 – TRỰC QUAN HÓA DỮ LIỆU
# ==================================================

# Import các thư viện cần thiết
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Đọc dữ liệu"""

winequality_red_data = pd.read_csv("winequality-red.csv")
winequality_red_data = winequality_red_data[['fixed acidity', 'volatile acidity', 'citric acid',
                                             'residual sugar', 'chlorides', 'free sulfur dioxide',
                                             'total sulfur dioxide', 'density', 'pH', 'sulphates',
                                             'alcohol', 'quality']]

"""# Kiểm tra thông tin dữ liệu"""

print("Thông tin dữ liệu:")
print(winequality_red_data.info())
print("\n5 dòng đầu tiên của dữ liệu:")
print(winequality_red_data.head())

"""
# Histogram – Phân bố của biến alcohol"""

winequality_red_data.hist(bins=15, figsize=(15, 10), color="#1A5276", edgecolor="black", alpha=0.85)
plt.suptitle("Phân phối các đặc trưng của rượu vang đỏ", fontsize=16, fontweight="bold", color="#1B2631")
plt.savefig("bieu do.png", dpi=300 )
plt.show()

"""# Boxplot – Phân bố các biến"""

plt.figure(figsize=(12, 7))
sns.boxplot(data=winequality_red_data, orient="h", palette="mako", linewidth=1.3, saturation=0.85)
plt.title("Phân bố các giá trị ngoại lai của các đặc trưng rượu vang đỏ",
          fontsize=16, fontweight="bold", color="#1B2631")
plt.xlabel("Giá trị đo lường", fontsize=12)
plt.ylabel("Đặc trưng hóa học", fontsize=12)
sns.despine()
plt.savefig("bieu do.png", dpi=300 )
plt.show()

"""#  Trực quan hóa đơn biến

# Phân bố chất lượng của rượu vang đỏ
"""

sns.set_style("whitegrid", {'axes.grid': False})
palette_colors = sns.color_palette("magma", n_colors=winequality_red_data["quality"].nunique())
plt.figure(figsize=(8, 5))
ax = sns.countplot(x="quality", data=winequality_red_data, palette=palette_colors, edgecolor="black", saturation=0.9)
for container in ax.containers:
    ax.bar_label(container, fmt='%d', label_type='edge', fontsize=10, padding=2, color='black')

plt.title("Phân bố chất lượng của rượu vang đỏ", fontsize=16, fontweight="bold", color="#1B2631")
plt.xlabel("Chất lượng (Quality)", fontsize=12)
plt.ylabel("Số lượng mẫu", fontsize=12)
sns.despine()
plt.tight_layout()
plt.show()

"""#  Trực quan hóa 2 biến

# Scatter plot – Alcohol và Quality
"""

sns.set_style("whitegrid", {'axes.grid': False})
plt.figure(figsize=(8, 6))
sns.scatterplot(x="alcohol", y="quality", data=winequality_red_data, hue="quality", palette="viridis", s=70, alpha=0.8, edgecolor="#1C2833", linewidth=0.4)
plt.title("Mối quan hệ giữa Alcohol và Quality (tô màu theo mức chất lượng)",
          fontsize=14, fontweight="bold", color="#1B2631")
plt.xlabel("Alcohol (%)", fontsize=12)
plt.ylabel("Quality", fontsize=12)
plt.legend(title="Quality", loc="lower right", frameon=False)
sns.despine()
plt.tight_layout()
plt.show()

"""# Boxplot - Phân bố Destiny theo Quality"""

sns.set_style("whitegrid", {'axes.grid': False})
plt.figure(figsize=(8, 6))
sns.boxplot(x="quality", y="density", data=winequality_red_data, palette="viridis", linewidth=1.3, saturation=0.9)
plt.title("Phân bố mật độ (Density) theo từng mức chất lượng (Quality)",
          fontsize=14, fontweight="bold", color="#1B2631")
plt.xlabel("Mức chất lượng (Quality)", fontsize=12)
plt.ylabel("Mật độ rượu (Density)", fontsize=12)
sns.despine()
plt.tight_layout()
plt.show()

"""
# Biểu đồ heatmap – ma trận tương quan giữa các biến"""

plt.figure(figsize=(10,8))
corr = winequality_red_data.corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Biểu đồ tương quan giữa các biến trong dữ liệu rượu vang đỏ")
plt.show()