# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E-WZNAcEdIZYa3bzk-Z5CicqQTLSan5O

# ==================================================
# BÀI 1.1.4 - Bài tập thực hành 2
# Thực hiện thống kê mô tả dữ liệu bệnh tiểu đường
# ==================================================

# 1. Import thư viện
"""

import numpy as np
import pandas as pd
from scipy import stats

"""# 2. Đọc dữ liệu"""

diabetes_data_datad = pd.read_csv("diabetes.csv")
diabetes_data = diabetes_data[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
                                             'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']]

"""
# 3. Quan sát sơ bộ dữ liệu"""

print("Kích thước dữ liệu:", diabetes_data.shape)
print("Tên các cột:", diabetes_data.columns.tolist())
display(diabetes_data.head())

"""# 4. Thống kê mô tả toàn bộ dữ liệu"""

print("\nThống kê mô tả tổng quát:")
display(diabetes_data.describe())

"""# Take a quick look at the data"""

diabetes_data.head()
diabetes_data.dtypes
diabetes_data.shape

"""# Get the mean of the data"""

data_mean = diabetes_data.mean()

"""# Get the median of the data"""

data_median = diabetes_data.median()

"""# Get the mode of the data"""

data_mode = diabetes_data.mode().iloc[0]

"""# Obtain the variance of the data"""

data_variance = diabetes_data.var()

"""# Obtain the standard deviation of the data"""

data_sd = diabetes_data.std()

"""# Compute the maximum and minimum values of the data"""

data_max = diabetes_data.max()
data_min = diabetes_data.min()

"""# Obtain the 60th percentile of the data"""

data_percentile = diabetes_data.quantile(0.6)

"""# Obtain the quartiles of the data"""

data_quartile = diabetes_data.quantile(0.75)

"""# Get the IQR of the data"""

data_IQR = data_quartile - diabetes_data.quantile(0.25)