# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sj_00f5fWDfbgwoTNeXsk3hDFMBfLzOj

# ==================================================
# BÀI 1.1.3 - Bài tập thực hành 1
# Thực hiện thống kê mô tả dữ liệu rượu đỏ
# ==================================================

# 1. Import thư viện
"""

import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

"""# 2. Đọc dữ liệu"""

winequality_red_data = pd.read_csv("winequality-red.csv")
winequality_red_data = winequality_red_data[['fixed acidity', 'volatile acidity', 'citric acid',
                                             'residual sugar', 'chlorides', 'free sulfur dioxide',
                                             'total sulfur dioxide', 'density', 'pH', 'sulphates',
                                             'alcohol', 'quality']]

"""# 3. Quan sát sơ bộ dữ liệu"""

print("Kích thước dữ liệu:", winequality_red_data.shape)
print("Tên các cột:", winequality_red_data.columns.tolist())
print("\n5 dòng đầu tiên của dữ liệu:")
display(winequality_red_data.head())

"""# 4. Kiểm tra kiểu dữ liệu và thông tin tổng quát"""

print("\nThông tin dữ liệu:")
print(winequality_red_data.info())

"""# 5. Thống kê mô tả toàn bộ dữ liệu"""

print("\nThống kê mô tả tổng quát:")
display(winequality_red_data.describe())

"""# Take a quick look at the data"""

winequality_red_data.head()
winequality_red_data.dtypes
winequality_red_data.shape

"""# Get the mean of the data"""

dataquality_red_mean = np.mean(wine_data["quality"])

"""# Get the median of the data"""

data_median = np.median(winequality_red_data["quality"])

"""# Get the mode of the data"""

data_mode = stats.mode(winequality_red_data["quality"], keepdims=True)
mode_value = data_mode.mode if np.isscalar(data_mode.mode) else data_mode.mode[0]

"""# Obtain the variance of the data"""

data_variance = np.var(winequality_red_data["quality"])

"""# Obtain the standard deviation of the data"""

data_sd = np.std(winequality_red_data["quality"])

"""# Compute the maximum and minimum values of the data"""

data_max = np.max(winequality_red_data["quality"])
data_min = np.min(winequality_red_data["quality"])

"""# Obtain the 60th percentile of the data"""

data_percentile = np.percentile(winequality_red_data["quality"],60)

"""# Obtain the quartiles of the data"""

data_quartile = np.quantile(winequality_red_data["quality"],0.75)

"""# Get the IQR of the data"""

data_IQR = stats.iqr(winequality_red_data["quality"])